print("Hello world!")
print("next tasks: set up replit")
print("She said: \"Hello\" and then left.")
print('She said: "Hello" and then left.')
print("Hello World!\nHelloWorld")
print("Hello" + " " + "Madina!")
